### PR TITLE
Feature/render prop pattern

### PR DESCRIPTION
**Pull request by adnan1naeem**
## What I did
Converted HOC according to RenderPropPattern
## How to test
By adding plugin  in App bluerain.js
Is this testable with jest or storyshots?
Test are written
Are any of the existing tests are failing ?
No
Does this need an update to the documentation?
no
Does it have breaking changes ?
no
If your answer is yes to any of these, please make sure to include it in your PR.

@bjavaid @amnajunaid please review the changes and merge them.

### CODE REVIEW

**Comment by bjavaid** [comment]
1. The Coverage thresholds are decreased too mush low. Increase the test coverage.
2. Check the BlueRain OS version. You are using alpha releases; it should be modified with the latest release
3. Check the Lint issues
4. Disabling the TS lint settings in the config file is not a good practice.

**Comment by adnan1naeem** [comment]
Please dont merge this branch  @bjavaid  as  it is merged in ssr mode branch

**Comment by adnan1naeem** [comment]
@bjavaid the feature of this pull request has been completed in ssr-mode

**Pull request closed without merging**
